// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6ITtnTHR6UgiFiZuDGUVUtDIC_l5azk',
    appId: '1:646327341922:web:b06e5871de38204d03d23b',
    messagingSenderId: '646327341922',
    projectId: 'scholar-chat-c0657',
    authDomain: 'scholar-chat-c0657.firebaseapp.com',
    storageBucket: 'scholar-chat-c0657.firebasestorage.app',
    measurementId: 'G-7WM8ZBMK0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOTQn7-krsZP-hHkvJZdYb94qRjr3xGA',
    appId: '1:646327341922:android:60506fc16a80133703d23b',
    messagingSenderId: '646327341922',
    projectId: 'scholar-chat-c0657',
    storageBucket: 'scholar-chat-c0657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0UR9sVNE2xom7YWSJUeXIpFfqFanIRTM',
    appId: '1:646327341922:ios:36b96f7f3a346ac403d23b',
    messagingSenderId: '646327341922',
    projectId: 'scholar-chat-c0657',
    storageBucket: 'scholar-chat-c0657.firebasestorage.app',
    iosBundleId: 'com.example.aChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0UR9sVNE2xom7YWSJUeXIpFfqFanIRTM',
    appId: '1:646327341922:ios:36b96f7f3a346ac403d23b',
    messagingSenderId: '646327341922',
    projectId: 'scholar-chat-c0657',
    storageBucket: 'scholar-chat-c0657.firebasestorage.app',
    iosBundleId: 'com.example.aChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw6ITtnTHR6UgiFiZuDGUVUtDIC_l5azk',
    appId: '1:646327341922:web:165a80550f75fb7003d23b',
    messagingSenderId: '646327341922',
    projectId: 'scholar-chat-c0657',
    authDomain: 'scholar-chat-c0657.firebaseapp.com',
    storageBucket: 'scholar-chat-c0657.firebasestorage.app',
    measurementId: 'G-F3L2V6T0B9',
  );
}
